// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: genx/creation/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AssetType int32

const (
	AssetType_TOKEN          AssetType = 0
	AssetType_NFT_COLLECTION AssetType = 1
	AssetType_MEME_COIN      AssetType = 2
	AssetType_CUSTOM_ASSET   AssetType = 3
)

var AssetType_name = map[int32]string{
	0: "TOKEN",
	1: "NFT_COLLECTION",
	2: "MEME_COIN",
	3: "CUSTOM_ASSET",
}

var AssetType_value = map[string]int32{
	"TOKEN":          0,
	"NFT_COLLECTION": 1,
	"MEME_COIN":      2,
	"CUSTOM_ASSET":   3,
}

func (x AssetType) String() string {
	return proto.EnumName(AssetType_name, int32(x))
}

func (AssetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bdae0d19eea4781, []int{0}
}

type BondingCurveType int32

const (
	BondingCurveType_LINEAR      BondingCurveType = 0
	BondingCurveType_EXPONENTIAL BondingCurveType = 1
	BondingCurveType_LOGARITHMIC BondingCurveType = 2
	BondingCurveType_SIGMOID     BondingCurveType = 3
)

var BondingCurveType_name = map[int32]string{
	0: "LINEAR",
	1: "EXPONENTIAL",
	2: "LOGARITHMIC",
	3: "SIGMOID",
}

var BondingCurveType_value = map[string]int32{
	"LINEAR":      0,
	"EXPONENTIAL": 1,
	"LOGARITHMIC": 2,
	"SIGMOID":     3,
}

func (x BondingCurveType) String() string {
	return proto.EnumName(BondingCurveType_name, int32(x))
}

func (BondingCurveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bdae0d19eea4781, []int{1}
}

type CreationTemplate struct {
	Id             string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AssetType      AssetType   `protobuf:"varint,3,opt,name=asset_type,json=assetType,proto3,enum=genx.creation.v1.AssetType" json:"asset_type,omitempty"`
	Description    string      `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	RequiredFields []string    `protobuf:"bytes,5,rep,name=required_fields,json=requiredFields,proto3" json:"required_fields,omitempty"`
	OptionalFields []string    `protobuf:"bytes,6,rep,name=optional_fields,json=optionalFields,proto3" json:"optional_fields,omitempty"`
	CreationFee    *types.Coin `protobuf:"bytes,7,opt,name=creation_fee,json=creationFee,proto3" json:"creation_fee,omitempty"`
}

func (m *CreationTemplate) Reset()         { *m = CreationTemplate{} }
func (m *CreationTemplate) String() string { return proto.CompactTextString(m) }
func (*CreationTemplate) ProtoMessage()    {}
func (*CreationTemplate) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bdae0d19eea4781, []int{0}
}
func (m *CreationTemplate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreationTemplate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreationTemplate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreationTemplate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreationTemplate.Merge(m, src)
}
func (m *CreationTemplate) XXX_Size() int {
	return m.Size()
}
func (m *CreationTemplate) XXX_DiscardUnknown() {
	xxx_messageInfo_CreationTemplate.DiscardUnknown(m)
}

var xxx_messageInfo_CreationTemplate proto.InternalMessageInfo

func (m *CreationTemplate) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreationTemplate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreationTemplate) GetAssetType() AssetType {
	if m != nil {
		return m.AssetType
	}
	return AssetType_TOKEN
}

func (m *CreationTemplate) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreationTemplate) GetRequiredFields() []string {
	if m != nil {
		return m.RequiredFields
	}
	return nil
}

func (m *CreationTemplate) GetOptionalFields() []string {
	if m != nil {
		return m.OptionalFields
	}
	return nil
}

func (m *CreationTemplate) GetCreationFee() *types.Coin {
	if m != nil {
		return m.CreationFee
	}
	return nil
}

type ReferralInfo struct {
	Referrer           string                      `protobuf:"bytes,1,opt,name=referrer,proto3" json:"referrer,omitempty"`
	Referee            string                      `protobuf:"bytes,2,opt,name=referee,proto3" json:"referee,omitempty"`
	ReferrerSpeedBoost cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=referrer_speed_boost,json=referrerSpeedBoost,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"referrer_speed_boost"`
	ReferralCount      int64                       `protobuf:"varint,4,opt,name=referral_count,json=referralCount,proto3" json:"referral_count,omitempty"`
	TotalRewards       int64                       `protobuf:"varint,5,opt,name=total_rewards,json=totalRewards,proto3" json:"total_rewards,omitempty"`
}

func (m *ReferralInfo) Reset()         { *m = ReferralInfo{} }
func (m *ReferralInfo) String() string { return proto.CompactTextString(m) }
func (*ReferralInfo) ProtoMessage()    {}
func (*ReferralInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bdae0d19eea4781, []int{1}
}
func (m *ReferralInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReferralInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReferralInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ReferralInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferralInfo.Merge(m, src)
}
func (m *ReferralInfo) XXX_Size() int {
	return m.Size()
}
func (m *ReferralInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferralInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReferralInfo proto.InternalMessageInfo

func (m *ReferralInfo) GetReferrer() string {
	if m != nil {
		return m.Referrer
	}
	return ""
}

func (m *ReferralInfo) GetReferee() string {
	if m != nil {
		return m.Referee
	}
	return ""
}

func (m *ReferralInfo) GetReferralCount() int64 {
	if m != nil {
		return m.ReferralCount
	}
	return 0
}

func (m *ReferralInfo) GetTotalRewards() int64 {
	if m != nil {
		return m.TotalRewards
	}
	return 0
}

type CreatedAsset struct {
	Id                    string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator               string                      `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	AssetType             string                      `protobuf:"bytes,3,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	Name                  string                      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Symbol                string                      `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Description           string                      `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Denom                 string                      `protobuf:"bytes,7,opt,name=denom,proto3" json:"denom,omitempty"`
	MetadataUri           string                      `protobuf:"bytes,8,opt,name=metadata_uri,json=metadataUri,proto3" json:"metadata_uri,omitempty"`
	CreatedAt             int64                       `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RoyaltyPercentage     cosmossdk_io_math.LegacyDec `protobuf:"bytes,10,opt,name=royalty_percentage,json=royaltyPercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"royalty_percentage"`
	LiquidationProtection bool                        `protobuf:"varint,11,opt,name=liquidation_protection,json=liquidationProtection,proto3" json:"liquidation_protection,omitempty"`
	BondingCurveType      string                      `protobuf:"bytes,12,opt,name=bonding_curve_type,json=bondingCurveType,proto3" json:"bonding_curve_type,omitempty"`
}

func (m *CreatedAsset) Reset()         { *m = CreatedAsset{} }
func (m *CreatedAsset) String() string { return proto.CompactTextString(m) }
func (*CreatedAsset) ProtoMessage()    {}
func (*CreatedAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bdae0d19eea4781, []int{2}
}
func (m *CreatedAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreatedAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreatedAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreatedAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedAsset.Merge(m, src)
}
func (m *CreatedAsset) XXX_Size() int {
	return m.Size()
}
func (m *CreatedAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedAsset.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedAsset proto.InternalMessageInfo

func (m *CreatedAsset) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreatedAsset) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CreatedAsset) GetAssetType() string {
	if m != nil {
		return m.AssetType
	}
	return ""
}

func (m *CreatedAsset) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreatedAsset) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *CreatedAsset) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreatedAsset) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *CreatedAsset) GetMetadataUri() string {
	if m != nil {
		return m.MetadataUri
	}
	return ""
}

func (m *CreatedAsset) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *CreatedAsset) GetLiquidationProtection() bool {
	if m != nil {
		return m.LiquidationProtection
	}
	return false
}

func (m *CreatedAsset) GetBondingCurveType() string {
	if m != nil {
		return m.BondingCurveType
	}
	return ""
}

type Params struct {
	TokenCreationFee         *types.Coin                 `protobuf:"bytes,1,opt,name=token_creation_fee,json=tokenCreationFee,proto3" json:"token_creation_fee,omitempty"`
	NftCreationFee           *types.Coin                 `protobuf:"bytes,2,opt,name=nft_creation_fee,json=nftCreationFee,proto3" json:"nft_creation_fee,omitempty"`
	MemeCreationFee          *types.Coin                 `protobuf:"bytes,3,opt,name=meme_creation_fee,json=memeCreationFee,proto3" json:"meme_creation_fee,omitempty"`
	PlatformFeePercentage    cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=platform_fee_percentage,json=platformFeePercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"platform_fee_percentage"`
	RoyaltyDefault           cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=royalty_default,json=royaltyDefault,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"royalty_default"`
	ReferralBoostPercentage  cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=referral_boost_percentage,json=referralBoostPercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"referral_boost_percentage"`
	ReferralRewardPercentage cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=referral_reward_percentage,json=referralRewardPercentage,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"referral_reward_percentage"`
	MaxAssetsPerCreator      uint64                      `protobuf:"varint,8,opt,name=max_assets_per_creator,json=maxAssetsPerCreator,proto3" json:"max_assets_per_creator,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bdae0d19eea4781, []int{3}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTokenCreationFee() *types.Coin {
	if m != nil {
		return m.TokenCreationFee
	}
	return nil
}

func (m *Params) GetNftCreationFee() *types.Coin {
	if m != nil {
		return m.NftCreationFee
	}
	return nil
}

func (m *Params) GetMemeCreationFee() *types.Coin {
	if m != nil {
		return m.MemeCreationFee
	}
	return nil
}

func (m *Params) GetMaxAssetsPerCreator() uint64 {
	if m != nil {
		return m.MaxAssetsPerCreator
	}
	return 0
}

type GenesisState struct {
	Params        *Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	CreatedAssets []*CreatedAsset `protobuf:"bytes,2,rep,name=created_assets,json=createdAssets,proto3" json:"created_assets,omitempty"`
	Referrals     []*ReferralInfo `protobuf:"bytes,3,rep,name=referrals,proto3" json:"referrals,omitempty"`
	AssetCount    uint64          `protobuf:"varint,4,opt,name=asset_count,json=assetCount,proto3" json:"asset_count,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bdae0d19eea4781, []int{4}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisState) GetCreatedAssets() []*CreatedAsset {
	if m != nil {
		return m.CreatedAssets
	}
	return nil
}

func (m *GenesisState) GetReferrals() []*ReferralInfo {
	if m != nil {
		return m.Referrals
	}
	return nil
}

func (m *GenesisState) GetAssetCount() uint64 {
	if m != nil {
		return m.AssetCount
	}
	return 0
}

func init() {
	proto.RegisterEnum("genx.creation.v1.AssetType", AssetType_name, AssetType_value)
	proto.RegisterEnum("genx.creation.v1.BondingCurveType", BondingCurveType_name, BondingCurveType_value)
	proto.RegisterType((*CreationTemplate)(nil), "genx.creation.v1.CreationTemplate")
	proto.RegisterType((*ReferralInfo)(nil), "genx.creation.v1.ReferralInfo")
	proto.RegisterType((*CreatedAsset)(nil), "genx.creation.v1.CreatedAsset")
	proto.RegisterType((*Params)(nil), "genx.creation.v1.Params")
	proto.RegisterType((*GenesisState)(nil), "genx.creation.v1.GenesisState")
}

func init() { proto.RegisterFile("genx/creation/v1/genesis.proto", fileDescriptor_8bdae0d19eea4781) }

var fileDescriptor_8bdae0d19eea4781 = []byte{
	// 1046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x4e, 0xe3, 0x46,
	0x14, 0x8e, 0x93, 0x10, 0xd6, 0x27, 0x21, 0x78, 0xa7, 0xfb, 0x63, 0x58, 0x35, 0xa4, 0xac, 0xaa,
	0x46, 0xa8, 0x72, 0x0a, 0xab, 0xde, 0x54, 0xbd, 0x09, 0x26, 0xd0, 0x68, 0xf3, 0x83, 0x9c, 0x20,
	0x55, 0xed, 0x85, 0x35, 0xb1, 0x4f, 0x82, 0xb5, 0xb1, 0x27, 0x6b, 0x4f, 0x28, 0xb9, 0xec, 0x1b,
	0xf4, 0x21, 0xfa, 0x0c, 0x7d, 0x86, 0xbd, 0xdc, 0xcb, 0xaa, 0x17, 0xab, 0x0a, 0xa4, 0xf6, 0x35,
	0xaa, 0x19, 0xdb, 0xc1, 0x80, 0x2a, 0xb8, 0xf3, 0xf9, 0xfb, 0xe6, 0xcc, 0x39, 0xdf, 0x39, 0x63,
	0xa8, 0x4d, 0x31, 0xb8, 0x6c, 0x3a, 0x21, 0x52, 0xee, 0xb1, 0xa0, 0x79, 0xb1, 0xdf, 0x9c, 0x62,
	0x80, 0x91, 0x17, 0x19, 0xf3, 0x90, 0x71, 0x46, 0x34, 0x61, 0x37, 0x52, 0xbb, 0x71, 0xb1, 0xbf,
	0xfd, 0x6c, 0xca, 0xa6, 0x4c, 0x1a, 0x9b, 0xe2, 0x2b, 0xf6, 0xdb, 0xae, 0x39, 0x2c, 0xf2, 0x59,
	0xd4, 0x1c, 0xd3, 0x08, 0x9b, 0x17, 0xfb, 0x63, 0xe4, 0x74, 0xbf, 0xe9, 0x30, 0x2f, 0x48, 0xec,
	0x5b, 0xb1, 0xdd, 0x8e, 0x03, 0x63, 0x21, 0x36, 0xed, 0xfe, 0x9e, 0x07, 0xcd, 0x4c, 0x0e, 0x18,
	0xa1, 0x3f, 0x9f, 0x51, 0x8e, 0xa4, 0x0a, 0x79, 0xcf, 0xd5, 0x95, 0xba, 0xd2, 0x50, 0xad, 0xbc,
	0xe7, 0x12, 0x02, 0xc5, 0x80, 0xfa, 0xa8, 0xe7, 0xa5, 0x46, 0x7e, 0x93, 0xef, 0x00, 0x68, 0x14,
	0x21, 0xb7, 0xf9, 0x72, 0x8e, 0x7a, 0xa1, 0xae, 0x34, 0xaa, 0x07, 0xaf, 0x8c, 0xbb, 0x09, 0x1b,
	0x2d, 0xe1, 0x33, 0x5a, 0xce, 0xd1, 0x52, 0x69, 0xfa, 0x49, 0xea, 0x50, 0x76, 0x31, 0x72, 0x42,
	0x6f, 0x2e, 0xdc, 0xf4, 0xa2, 0x84, 0xcd, 0xaa, 0xc8, 0x57, 0xb0, 0x19, 0xe2, 0xfb, 0x85, 0x17,
	0xa2, 0x6b, 0x4f, 0x3c, 0x9c, 0xb9, 0x91, 0xbe, 0x56, 0x2f, 0x34, 0x54, 0xab, 0x9a, 0xaa, 0x8f,
	0xa5, 0x56, 0x38, 0x32, 0x19, 0x42, 0x67, 0xa9, 0x63, 0x29, 0x76, 0x4c, 0xd5, 0x89, 0xe3, 0xf7,
	0x50, 0x49, 0xf3, 0xb2, 0x27, 0x88, 0xfa, 0x7a, 0x5d, 0x69, 0x94, 0x0f, 0xb6, 0x8c, 0xa4, 0x1a,
	0xa2, 0x74, 0x46, 0x52, 0x3a, 0xc3, 0x64, 0x5e, 0x60, 0x95, 0x53, 0xf7, 0x63, 0xc4, 0xdd, 0x7f,
	0x15, 0xa8, 0x58, 0x38, 0xc1, 0x30, 0xa4, 0xb3, 0x4e, 0x30, 0x61, 0x64, 0x1b, 0x9e, 0x84, 0x52,
	0xc6, 0x30, 0x29, 0xd4, 0x4a, 0x26, 0x3a, 0xac, 0xcb, 0x6f, 0x4c, 0x2b, 0x96, 0x8a, 0xe4, 0x0c,
	0x9e, 0xa5, 0x5e, 0x76, 0x34, 0x47, 0x74, 0xed, 0x31, 0x63, 0x11, 0x97, 0xe5, 0x53, 0x0f, 0x5f,
	0x7f, 0xf8, 0xb4, 0x93, 0xfb, 0xeb, 0xd3, 0xce, 0xab, 0x38, 0xa7, 0xc8, 0x7d, 0x67, 0x78, 0xac,
	0xe9, 0x53, 0x7e, 0x6e, 0x74, 0x71, 0x4a, 0x9d, 0xe5, 0x11, 0x3a, 0x16, 0x49, 0x01, 0x86, 0x22,
	0xfe, 0x50, 0x84, 0x93, 0x2f, 0xa1, 0x1a, 0x26, 0xc9, 0xd9, 0x0e, 0x5b, 0x04, 0x5c, 0x96, 0xb4,
	0x60, 0x6d, 0xa4, 0x5a, 0x53, 0x28, 0xc9, 0x6b, 0xd8, 0xe0, 0x8c, 0xd3, 0x99, 0x1d, 0xe2, 0x2f,
	0x34, 0x94, 0x25, 0x15, 0x5e, 0x15, 0xa9, 0xb4, 0x62, 0xdd, 0xee, 0x1f, 0x05, 0xa8, 0x48, 0x42,
	0xa0, 0x2b, 0x7b, 0x77, 0x8f, 0x0c, 0x3a, 0xac, 0xcb, 0xca, 0xb0, 0x30, 0xbd, 0x5d, 0x22, 0x92,
	0xcf, 0xef, 0x51, 0x42, 0xcd, 0x76, 0x3d, 0x65, 0x51, 0x31, 0xc3, 0xa2, 0x17, 0x50, 0x8a, 0x96,
	0xfe, 0x98, 0xcd, 0x64, 0x2e, 0xaa, 0x95, 0x48, 0x77, 0x19, 0x52, 0xba, 0xcf, 0x90, 0x67, 0xb0,
	0xe6, 0x62, 0xc0, 0x7c, 0xd9, 0x48, 0xd5, 0x8a, 0x05, 0xf2, 0x05, 0x54, 0x7c, 0xe4, 0xd4, 0xa5,
	0x9c, 0xda, 0x8b, 0xd0, 0xd3, 0x9f, 0xc4, 0x81, 0xa9, 0xee, 0x2c, 0xf4, 0x44, 0x96, 0x4e, 0x7c,
	0x3f, 0x9b, 0x72, 0x5d, 0x95, 0x25, 0x50, 0x13, 0x4d, 0x8b, 0x13, 0x0b, 0x48, 0xc8, 0x96, 0x74,
	0xc6, 0x97, 0xf6, 0x1c, 0x43, 0x07, 0x03, 0x4e, 0xa7, 0xa8, 0xc3, 0xe3, 0x1b, 0xf4, 0x34, 0x09,
	0x3f, 0x5d, 0x45, 0x93, 0x6f, 0xe1, 0xc5, 0xcc, 0x7b, 0xbf, 0xf0, 0xdc, 0x98, 0x7e, 0x62, 0xf2,
	0xd0, 0x91, 0x17, 0x2b, 0xd7, 0x95, 0xc6, 0x13, 0xeb, 0x79, 0xc6, 0x7a, 0xba, 0x32, 0x92, 0xaf,
	0x81, 0x8c, 0x59, 0xe0, 0x7a, 0xc1, 0xd4, 0x76, 0x16, 0xe1, 0x05, 0xc6, 0x75, 0xad, 0xc8, 0x2b,
	0x69, 0x89, 0xc5, 0x14, 0x06, 0x51, 0xde, 0xdd, 0x5f, 0xd7, 0xa0, 0x74, 0x4a, 0x43, 0xea, 0x47,
	0xe4, 0x04, 0x08, 0x67, 0xef, 0x30, 0xb0, 0x6f, 0x31, 0x5e, 0x79, 0x88, 0xf1, 0x9a, 0x0c, 0x32,
	0x6f, 0x68, 0x4f, 0x4c, 0xd0, 0x82, 0x09, 0xbf, 0x0d, 0x93, 0x7f, 0x08, 0xa6, 0x1a, 0x4c, 0x78,
	0x16, 0xa4, 0x0d, 0x4f, 0x7d, 0xf4, 0xf1, 0x36, 0x4a, 0xe1, 0x21, 0x94, 0x4d, 0x11, 0x93, 0x85,
	0xf9, 0x19, 0x5e, 0x8a, 0xed, 0x34, 0x61, 0xa1, 0x2f, 0x10, 0xb2, 0xdd, 0x29, 0x3e, 0xbe, 0x3b,
	0xcf, 0x53, 0x8c, 0x63, 0xc4, 0x4c, 0x87, 0xba, 0xb0, 0x99, 0x76, 0xdd, 0xc5, 0x09, 0x5d, 0xcc,
	0x78, 0x4c, 0xc8, 0xc7, 0x81, 0x56, 0x93, 0xd8, 0xa3, 0x38, 0x94, 0xd8, 0xb0, 0xb5, 0x9a, 0x47,
	0x39, 0xe0, 0xd9, 0x64, 0x4b, 0x8f, 0xc7, 0x7d, 0x99, 0xa2, 0xc8, 0x31, 0xcf, 0xa4, 0x4b, 0x61,
	0x7b, 0x75, 0x40, 0x3c, 0xcc, 0xd9, 0x13, 0xd6, 0x1f, 0x7f, 0x82, 0x9e, 0xc2, 0xc4, 0xe3, 0x9f,
	0x39, 0xe2, 0x0d, 0xbc, 0xf0, 0xe9, 0xa5, 0x2d, 0xc7, 0x37, 0x12, 0xe8, 0x76, 0x3a, 0xf5, 0x62,
	0xa6, 0x8a, 0xd6, 0x67, 0x3e, 0xbd, 0x94, 0x0b, 0x22, 0x3a, 0xc5, 0xd0, 0x8c, 0x4d, 0xbb, 0xff,
	0x28, 0x50, 0x39, 0x89, 0x9f, 0xb0, 0x21, 0x17, 0x2f, 0xc9, 0x37, 0x50, 0x9a, 0x4b, 0x4e, 0x26,
	0xec, 0xd3, 0xef, 0xbf, 0x10, 0x31, 0x67, 0xad, 0xc4, 0x8f, 0xb4, 0xa1, 0xba, 0x1a, 0x4f, 0x09,
	0xaf, 0xe7, 0xeb, 0x85, 0x46, 0xf9, 0xa0, 0x76, 0x3f, 0x32, 0xbb, 0xa6, 0xac, 0x0d, 0x27, 0x23,
	0x89, 0x75, 0xaf, 0xa6, 0x57, 0x8b, 0xf4, 0xc2, 0xff, 0x21, 0x64, 0x57, 0xba, 0x75, 0x13, 0x40,
	0x76, 0xa0, 0x1c, 0x6f, 0xb2, 0x9b, 0x6d, 0x5a, 0xb4, 0xe2, 0xe5, 0x26, 0x57, 0xe9, 0xde, 0x5b,
	0x50, 0x57, 0x2f, 0x1b, 0x51, 0x61, 0x6d, 0x34, 0x78, 0xdb, 0xee, 0x6b, 0x39, 0x42, 0xa0, 0xda,
	0x3f, 0x1e, 0xd9, 0xe6, 0xa0, 0xdb, 0x6d, 0x9b, 0xa3, 0xce, 0xa0, 0xaf, 0x29, 0x64, 0x03, 0xd4,
	0x5e, 0xbb, 0xd7, 0xb6, 0xcd, 0x41, 0xa7, 0xaf, 0xe5, 0x89, 0x06, 0x15, 0xf3, 0x6c, 0x38, 0x1a,
	0xf4, 0xec, 0xd6, 0x70, 0xd8, 0x1e, 0x69, 0x85, 0xbd, 0x1e, 0x68, 0x87, 0x77, 0xa6, 0x99, 0x00,
	0x94, 0xba, 0x9d, 0x7e, 0xbb, 0x65, 0x69, 0x39, 0xb2, 0x09, 0xe5, 0xf6, 0x8f, 0xa7, 0x83, 0x7e,
	0xbb, 0x3f, 0xea, 0xb4, 0xba, 0x9a, 0x22, 0x14, 0xdd, 0xc1, 0x49, 0xcb, 0xea, 0x8c, 0x7e, 0xe8,
	0x75, 0x4c, 0x2d, 0x4f, 0xca, 0xb0, 0x3e, 0xec, 0x9c, 0xf4, 0x06, 0x9d, 0x23, 0xad, 0x70, 0x78,
	0xf4, 0xe1, 0xaa, 0xa6, 0x7c, 0xbc, 0xaa, 0x29, 0x7f, 0x5f, 0xd5, 0x94, 0xdf, 0xae, 0x6b, 0xb9,
	0x8f, 0xd7, 0xb5, 0xdc, 0x9f, 0xd7, 0xb5, 0xdc, 0x4f, 0x7b, 0x53, 0x8f, 0x9f, 0x2f, 0xc6, 0x86,
	0xc3, 0xfc, 0xa6, 0x43, 0xe7, 0xe8, 0x9c, 0x53, 0x2f, 0x68, 0xca, 0x9f, 0x90, 0xcc, 0x6f, 0x88,
	0xd8, 0x32, 0xd1, 0xb8, 0x24, 0xff, 0x0f, 0xde, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0x55, 0xd1,
	0xd7, 0x64, 0xa4, 0x08, 0x00, 0x00,
}

func (m *CreationTemplate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreationTemplate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreationTemplate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreationFee != nil {
		{
			size, err := m.CreationFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.OptionalFields) > 0 {
		for iNdEx := len(m.OptionalFields) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OptionalFields[iNdEx])
			copy(dAtA[i:], m.OptionalFields[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.OptionalFields[iNdEx])))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.RequiredFields) > 0 {
		for iNdEx := len(m.RequiredFields) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.RequiredFields[iNdEx])
			copy(dAtA[i:], m.RequiredFields[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.RequiredFields[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x22
	}
	if m.AssetType != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AssetType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ReferralInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReferralInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ReferralInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TotalRewards != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TotalRewards))
		i--
		dAtA[i] = 0x28
	}
	if m.ReferralCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ReferralCount))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.ReferrerSpeedBoost.Size()
		i -= size
		if _, err := m.ReferrerSpeedBoost.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Referee) > 0 {
		i -= len(m.Referee)
		copy(dAtA[i:], m.Referee)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Referee)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Referrer) > 0 {
		i -= len(m.Referrer)
		copy(dAtA[i:], m.Referrer)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Referrer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CreatedAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreatedAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CreatedAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BondingCurveType) > 0 {
		i -= len(m.BondingCurveType)
		copy(dAtA[i:], m.BondingCurveType)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.BondingCurveType)))
		i--
		dAtA[i] = 0x62
	}
	if m.LiquidationProtection {
		i--
		if m.LiquidationProtection {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x58
	}
	{
		size := m.RoyaltyPercentage.Size()
		i -= size
		if _, err := m.RoyaltyPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	if m.CreatedAt != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if len(m.MetadataUri) > 0 {
		i -= len(m.MetadataUri)
		copy(dAtA[i:], m.MetadataUri)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MetadataUri)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AssetType) > 0 {
		i -= len(m.AssetType)
		copy(dAtA[i:], m.AssetType)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.AssetType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxAssetsPerCreator != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.MaxAssetsPerCreator))
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.ReferralRewardPercentage.Size()
		i -= size
		if _, err := m.ReferralRewardPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.ReferralBoostPercentage.Size()
		i -= size
		if _, err := m.ReferralBoostPercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.RoyaltyDefault.Size()
		i -= size
		if _, err := m.RoyaltyDefault.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.PlatformFeePercentage.Size()
		i -= size
		if _, err := m.PlatformFeePercentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.MemeCreationFee != nil {
		{
			size, err := m.MemeCreationFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.NftCreationFee != nil {
		{
			size, err := m.NftCreationFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.TokenCreationFee != nil {
		{
			size, err := m.TokenCreationFee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AssetCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AssetCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Referrals) > 0 {
		for iNdEx := len(m.Referrals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Referrals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.CreatedAssets) > 0 {
		for iNdEx := len(m.CreatedAssets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreatedAssets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CreationTemplate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.AssetType != 0 {
		n += 1 + sovGenesis(uint64(m.AssetType))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.RequiredFields) > 0 {
		for _, s := range m.RequiredFields {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.OptionalFields) > 0 {
		for _, s := range m.OptionalFields {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.CreationFee != nil {
		l = m.CreationFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *ReferralInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Referrer)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Referee)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.ReferrerSpeedBoost.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.ReferralCount != 0 {
		n += 1 + sovGenesis(uint64(m.ReferralCount))
	}
	if m.TotalRewards != 0 {
		n += 1 + sovGenesis(uint64(m.TotalRewards))
	}
	return n
}

func (m *CreatedAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.AssetType)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.MetadataUri)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovGenesis(uint64(m.CreatedAt))
	}
	l = m.RoyaltyPercentage.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.LiquidationProtection {
		n += 2
	}
	l = len(m.BondingCurveType)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TokenCreationFee != nil {
		l = m.TokenCreationFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.NftCreationFee != nil {
		l = m.NftCreationFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.MemeCreationFee != nil {
		l = m.MemeCreationFee.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.PlatformFeePercentage.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.RoyaltyDefault.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ReferralBoostPercentage.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.ReferralRewardPercentage.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.MaxAssetsPerCreator != 0 {
		n += 1 + sovGenesis(uint64(m.MaxAssetsPerCreator))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.CreatedAssets) > 0 {
		for _, e := range m.CreatedAssets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Referrals) > 0 {
		for _, e := range m.Referrals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.AssetCount != 0 {
		n += 1 + sovGenesis(uint64(m.AssetCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CreationTemplate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreationTemplate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreationTemplate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetType", wireType)
			}
			m.AssetType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetType |= AssetType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequiredFields", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RequiredFields = append(m.RequiredFields, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionalFields", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OptionalFields = append(m.OptionalFields, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreationFee == nil {
				m.CreationFee = &types.Coin{}
			}
			if err := m.CreationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReferralInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReferralInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReferralInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferrerSpeedBoost", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReferrerSpeedBoost.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralCount", wireType)
			}
			m.ReferralCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReferralCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRewards", wireType)
			}
			m.TotalRewards = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalRewards |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreatedAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreatedAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreatedAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataUri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataUri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoyaltyPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RoyaltyPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationProtection", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LiquidationProtection = bool(v != 0)
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondingCurveType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BondingCurveType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TokenCreationFee == nil {
				m.TokenCreationFee = &types.Coin{}
			}
			if err := m.TokenCreationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NftCreationFee == nil {
				m.NftCreationFee = &types.Coin{}
			}
			if err := m.NftCreationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemeCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MemeCreationFee == nil {
				m.MemeCreationFee = &types.Coin{}
			}
			if err := m.MemeCreationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformFeePercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PlatformFeePercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoyaltyDefault", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RoyaltyDefault.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralBoostPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReferralBoostPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferralRewardPercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReferralRewardPercentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxAssetsPerCreator", wireType)
			}
			m.MaxAssetsPerCreator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxAssetsPerCreator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAssets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAssets = append(m.CreatedAssets, &CreatedAsset{})
			if err := m.CreatedAssets[len(m.CreatedAssets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Referrals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Referrals = append(m.Referrals, &ReferralInfo{})
			if err := m.Referrals[len(m.Referrals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetCount", wireType)
			}
			m.AssetCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AssetCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
