#!/bin/bash
# Configure Oracle Cloud Security List for GenX Blockchain
# Run this on your local machine after setting up OCI CLI

echo "=========================================="
echo "  Oracle Cloud - Open GenX Ports"
echo "=========================================="
echo ""
echo "You need to open these ports in Oracle Cloud Console:"
echo ""
echo "1. Go to: https://cloud.oracle.com"
echo "2. Navigate to: Networking → Virtual Cloud Networks"
echo "3. Click on your VCN → Security Lists → Default Security List"
echo "4. Add Ingress Rules for each port below:"
echo ""
echo "PORT    PROTOCOL   SOURCE      PURPOSE"
echo "----------------------------------------"
echo "26656   TCP        0.0.0.0/0   P2P Node Communication"
echo "26657   TCP        0.0.0.0/0   RPC (Mobile App Connection)"
echo "1317    TCP        0.0.0.0/0   REST API (Wallet Queries)"
echo "26660   TCP        0.0.0.0/0   Prometheus (Monitoring)"
echo ""
echo "Example Ingress Rule:"
echo "  Source CIDR: 0.0.0.0/0"
echo "  IP Protocol: TCP"
echo "  Source Port Range: (leave blank)"
echo "  Destination Port Range: 26657"
echo "  Description: GenX RPC"
echo ""
echo "=========================================="
echo ""
echo "Alternative: Use OCI CLI (if configured):"
echo ""
echo "oci network security-list update \\"
echo "  --region <your-region> \\"
echo "  --compartment-id <compartment-ocid> \\"
echo "  --vcn-id <vcn-ocid> \\"
echo "  --security-list-id <security-list-ocid> \\"
echo "  --ingress-security-rules '["
echo "    {\"source\": \"0.0.0.0/0\", \"protocol\": \"6\", \"isStateless\": false,"
echo "     \"tcpOptions\": {\"destinationPortRange\": {\"min\": 26656, \"max\": 26657}},"
echo "    {\"source\": \"0.0.0.0/0\", \"protocol\": \"6\", \"isStateless\": false,"
echo "     \"tcpOptions\": {\"destinationPortRange\": {\"min\": 1317, \"max\": 1317}}}"
echo "  ]'"
echo ""
echo "=========================================="
